# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iatk.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\niatk.proto\x12\x04main\"m\n\x19PhysicalIdFromStackParams\x12\x1b\n\x13logical_resource_id\x18\x01 \x02(\t\x12\x12\n\nstack_name\x18\x02 \x02(\t\x12\x0f\n\x07profile\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\"\x90\x01\n\x07Request\x12\x0f\n\x07jsonrpc\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\t\x12\x0e\n\x06method\x18\x03 \x02(\t\x12/\n\x06params\x18\x04 \x02(\x0b\x32\x1f.main.PhysicalIdFromStackParams\x12\'\n\x08metadata\x18\x05 \x02(\x0b\x32\x15.main.RequestMetadata\"Z\n\x0fRequestMetadata\x12\x0e\n\x06\x63lient\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\t\x12\x0e\n\x06\x63\x61ller\x18\x03 \x02(\t\x12\x16\n\x0e\x63lient_version\x18\x04 \x02(\t\"X\n\x08Response\x12\x0f\n\x07jsonrpc\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\t\x12/\n\x06output\x18\x03 \x02(\x0b\x32\x1f.main.PhysicalIdFromStackOutput\"0\n\x19PhysicalIdFromStackOutput\x12\x13\n\x0bphysical_id\x18\x01 \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iatk_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PHYSICALIDFROMSTACKPARAMS']._serialized_start=20
  _globals['_PHYSICALIDFROMSTACKPARAMS']._serialized_end=129
  _globals['_REQUEST']._serialized_start=132
  _globals['_REQUEST']._serialized_end=276
  _globals['_REQUESTMETADATA']._serialized_start=278
  _globals['_REQUESTMETADATA']._serialized_end=368
  _globals['_RESPONSE']._serialized_start=370
  _globals['_RESPONSE']._serialized_end=458
  _globals['_PHYSICALIDFROMSTACKOUTPUT']._serialized_start=460
  _globals['_PHYSICALIDFROMSTACKOUTPUT']._serialized_end=508
# @@protoc_insertion_point(module_scope)
